void SolidColor()
{
  for (byte i=0; i<NUM_LEDS_TORRE; i++){
    ledsTorre_1[i]=CHSV(CENTELLEO,ENFRIAMIENTO,BRILLO);
    ledsTorre_2[i]=CHSV(CENTELLEO,ENFRIAMIENTO,BRILLO);
    ledsTorre_3[i]=CHSV(CENTELLEO,ENFRIAMIENTO,BRILLO);
    ledsTorre_4[i]=CHSV(CENTELLEO,ENFRIAMIENTO,BRILLO);
  }
}

